### ISSUE TITLE
Use authlib for the oauth flow

### ISSUE THREAD

**Issue by gabn88** [affiliprint/django-exact#13]
The way it is currently made it is hard to change where to store the access_token, etc. This makes it hard to use this package in an existing project where authlib is used for the oauth flow.

Would a PR to make these change easier be accepted?

EDIT: For example the DjangoStorage isn't used anywhere

**Comment by maldn** [comment]
I don't think i quite understand the use-case.
To make the session storage pluggable instead of using the Session model provided?

The DjangoStorage stuff is old and probably not used by anyone. I probably should just remove that
