### ISSUE TITLE
"expected string or bytes-like object" @ /exact/authenticate - after successful authentication

### ISSUE THREAD

**Issue by SebJansen** [affiliprint/django-exact#2]
Request Method: | GET
http://127.0.0.1:8000/exact/authenticate
1.11.5
TypeError
expected string or bytes-like object

https://imgur.com/a/e9iub

**Comment by SebJansen** [comment]
I think your package is incompatible with the latest Python version (3.6.3).

**Comment by maldn** [comment]
I only tested/using this with python 2.7.

If you can give me more details (stacktrace) i am sure this is easy to fix

**Comment by SebJansen** [comment]
https://gist.github.com/SebJansen/a00bb9c889a0cbfd913755113d613f7d

Thanks a lot. You rock!

**Comment by maldn** [comment]
thanks. i will look into this later this week.
in the meantime, you can try prefixing EXACT_ONLINE_CLIENT_SECRET and maybe EXACT_ONLINE_CLIENT_ID with b i.e. EXACT_ONLINE_CLIENT_SECRET = b"xxxx"
so make them bytestrings and not unicode. maybe this works around it,  but just a guess at this time.

**Comment by SebJansen** [comment]
Cheers! :)

Unfortunately, it doesn't fix the issue when run in a Python 3.x virtualenv.

**Comment by maldn** [comment]
i found the issue. i already uploaded a new version to pypi in case you dont use this repo directly.
please let me know if this fixes it or if any other issues come up.

**Comment by SebJansen** [comment]
That solved it. Thank you!
