### ISSUE TITLE
Django 4 compatibility

### ISSUE THREAD

**Issue by MaartenUreel** [affiliprint/django-exact#6]
Hello

to make this compatible with Django 4, I changed your urls.py:
```
# -*- coding: utf-8 -*-
from django.urls import re_path

from .views import Authenticate, Status, webhook

urlpatterns = [
    re_path(r"^authenticate$", Authenticate.as_view(), name="authenticate"),
    re_path(r"^status", Status.as_view(), name="status"),
    re_path(r"^webhook", webhook, name="webhook"),
]
```

So essentially changed the first import and used `re_path`.

Maybe you can make your library compatible with Django 4 this way.

**Comment by vitalik** [comment]
@maldn I see you fixed this - could you push it to pypi ?

**Comment by maldn** [comment]
thanks for the reminder. New 0.5.0 version is now on pypi.
